### ISSUE TITLE
Botones para tareas en V-REP

### ISSUE THREAD

**Issue by gandres2003** [juanps90/pgrado#14]
Se deben agregar botones para poder seleccionar la tarea a ejecutar (que se va a levantar desde un XML previamente salvado) y otro botón para finalizar una demo (y así crear un XML con la persistencia de la demostración)

**Comment by gandres2003** [comment]
Gustavo E había creado los botones y yo puse un editBox que permite escrbir un nombre para salvar la tarea actual o para ejecutar una tarea específica. 
Si bien no tiene controles de seguridad alguna (falla si se deja vacío o si se pide una tarea inexistente) por ahora funciona si no lo queremos romper a propósito.

**Comment by gevovlockas** [comment]
Hubo problemas con la escena ttt. Me dio conflicto y subí dos. Una con editBox pero sin la nueva configuración de la cámara. Otra al revés. Hay que juntarla en una. No se que es lo mas fácil. Si lo tuyo lo agregas rápido entonces hacelo sino charlamos de tarde y vemos como solucionamos.

-----Mensaje original-----
De: "gandres2003" notifications@github.com
Enviado el: ‎20/‎03/‎2016 0:23
Para: "juanps90/pgrado" pgrado@noreply.github.com
Asunto: Re: [pgrado] Botones para tareas en V-REP (#14)

Gustavo E había creado los botones y yo puse un editBox que permite escrbir un nombre para salvar la tarea actual o para ejecutar una tarea específica. 
Si bien no tiene controles de seguridad alguna (falla si se deja vacío o si se pide una tarea inexistente) por ahora funciona si no lo queremos romper a propósito.

**Comment by gevovlockas** [comment]
Para ahora que pienso que lo único que toque yo es la cámara asi que reviso de tarde si puedo juntarlo fácilmente.

-----Mensaje original-----
De: "gandres2003" notifications@github.com
Enviado el: ‎20/‎03/‎2016 0:23
Para: "juanps90/pgrado" pgrado@noreply.github.com
Asunto: Re: [pgrado] Botones para tareas en V-REP (#14)

Gustavo E había creado los botones y yo puse un editBox que permite escrbir un nombre para salvar la tarea actual o para ejecutar una tarea específica. 
Si bien no tiene controles de seguridad alguna (falla si se deja vacío o si se pide una tarea inexistente) por ahora funciona si no lo queremos romper a propósito.
