### ISSUE TITLE
Enviar tolerancias

### ISSUE THREAD

**Issue by juaneliel** [juanps90/pgrado#15]
hay dos metodos que verifican los parametros en el LCS y en el maestro compararparametros() deberian enviarse el id del sensor los valores sensados y la tolerancia de modo de comparar los valores y teniendo la tolerancia decidir si son o no el mismo comportamiento, el color tiene tolerancia 0 ya que son calores discretos

**Comment by juanps90** [comment]
Yo creo que, hay que decidir si la tolerancia la vamos a hacer a nivel de atributo, ie Valor(5.9).igual(6) = True, o si lo vamos a hacer a nivel de comportamiento, o de las dos maneras, o sea en la funcion igualComportamiento en comportamiento.py haría, para el caso de irAObjeto: color1.igual(color2) and distancia1.igual(color2) ...

Lo que yo creo que no es necesario pasar un parámetro, a menos que querramos poder cambiar al vuelo "el nivel de tolerancia", que puede ser útil para ver cómo se comporta el robot de una u otra manera.

**Comment by juaneliel** [comment]
Podés harcodear la tolerancia por atributo una distancia de 5 cm un ángulo de 0.2 ..para qe dos comportamientos sean iguales deberían cumplir que son iguales los datos sensados por los sensores considerando la tolerancia al error en el lcs hay un intento de algoritmo fíjate a ver que. Te parece comparar creo se llama

**Comment by juanps90** [comment]
Bueno, estuve haciendo unos cambios, pero al final creo que lo mejor sería algo así:
1. Hacemos unas clases para los atributos: Colores, Ángulos, etc.
2. Hacemos unas clases para los sensores: HeadSensor, Ultrasonic...
3. Hacemos un similar en sensores: HeadSensor.similar() 
4. El similar en sensores llama a similar() de cada uno de los atributos, ie: Color(1).similar(Color(2))

Estoy mirando el irA.py y analizando qué es lo que conviene hacer. Todavía no logro ver cómo reestructurar con la línea que dice:
cond0=  headSensor[1] in self.colorValido 

Voy a hacer las clases de sensores y ver de que quede todo de la manera más estructurada.

**Comment by juanps90** [comment]
Las tolerancias van a quedar hardcodeadas dentro de cada clase **de cada atributo**, aunque se podría hacer muy fácilmente parametrizable.

La "no tolerancia" del color, quedaria registrado en Color.py.

**Comment by juanps90** [comment]
Hice el cambio en el lcs.py
