### ISSUE TITLE
IrA pierde objeto cuando este esta muy sobre los bordes de imagen

### ISSUE THREAD

**Issue by gevovlockas** [juanps90/pgrado#19]
IrA pierde objeto cuando este esta muy sobre los bordes de imagen. Esto se debe a que cuando esta muy sobre el borde de la imagen hace un forward para acercarse pero se sale de la imagen entonces vuelve a hacer wander. Yo cambie para que no haga forward sino que gire pero se ve que algo quedo mal porque aun da problemas.

**Comment by juaneliel** [comment]
la secuencia para ir a un objeto se podria cambiar a> centrar al objeto luego avanzar hasta la distancia y luego ajustar el angulo, hoy dia no hace lo de centrar y arranca, esto se soluciona centrando

**Comment by juaneliel** [comment]
lo que estaria bueno que quien abrio los issue los cierre al comprobar si anda, creo que esto anda pero confirmalo por favor Gustavo

**Comment by gevovlockas** [comment]
Solucionado
