### ISSUE TITLE
Persistir calibracion

### ISSUE THREAD

**Issue by juaneliel** [juanps90/pgrado#21]
se necesita persistir un diccionario que ponee clave idColor, dos array de 3 elementos como valor

**Comment by gandres2003** [comment]
Lo voy a agregar dentro de los procedimientos de persistencia. 2 scripts, uno para salvar y otro para guardar cada XML que precisemos, por ahora, calibración y grafos)

**Comment by gandres2003** [comment]
Cerrado con el commit que acabo de hacer.
