### ISSUE TITLE
Mas de un objeto en IrA

### ISSUE THREAD

**Issue by juaneliel** [juanps90/pgrado#22]
Se debe acomodar metodo getAction ( y quien lo llama para que pase todos los datos de objetos vistos hos solo se le pasa datos del primer objeto aunque ya le llegan tods desde el input) para que contemple la deteccion de mas de un color en la escena

**Comment by juanps90** [comment]
Con gusto me encargo de esto. Todavía no estoy entendiendo bien cómo está estructurado. Me estoy perdiendo un poco en las llamadas.

**Comment by juaneliel** [comment]
al llegar de los sensores una señal se encarga atender sensores que verifica si se cumplen las condiciones y llama a actuar (que verifica ademas si se cumple el nivel mayor a cero) en el caso de irA actuar llama a findObject, que ve qeu accion realizar llamando al metodo getAction, lo que pasa hoy dia es que esta para evaluar un solo objeto visto el primero, la estructura ya envia varios objetos en el sensor head, enviando para cada objeto un par de distancia color (o al reves no recuerdo) entonces habria que ver si en la imagen entre los colores vistos esta el que es objetivo y en ese caso centrar la imagen al objeto y avanzar, al llegar a la distancia deseada rotar hasta alcanzar el angulo...esta hecho y anda bien el acercarse a la distancia y luego buscar el angulo..lo que no esta hecho es centrar antes de avanzar al ver el color ya que hoy dia solo avanza...resumiendo ver como resolver que hacer al ver varios objetos ya que tambien hay que evitar chocar con un objeto al ir en busca del objetivo

**Comment by gevovlockas** [comment]
A perdon no me di cuenta que estaba asignado a JP y lo arregle.

**Comment by juanps90** [comment]
Impecable!
