### ISSUE TITLE
Error al ejecutar una tarea.

### ISSUE THREAD

**Issue by gevovlockas** [juanps90/pgrado#23]
Cuando intento ejecutar una tarea desde el xml me da el error:
iniciando maestro
diccionario comportamientos  ['localizar', 'irA', 'avanzar', 'init']
inicio master
recibo comando 3|jose_0 1
comando  ejecutar
Traceback (most recent call last):
  File "/home/viki/catkin_ws/src/learning_by_imitation/scripts/maestro.py", line 1071, in <module>
    ejecutar()
  File "/home/viki/catkin_ws/src/learning_by_imitation/scripts/maestro.py", line 971, in ejecutar
    lcs.cargarEstructuras(idTarea) #se le deberia pasar id de la tarea a cargar
  File "/home/viki/pgrado/learning_by_imitation/scripts/lcs.py", line 421, in cargarEstructuras
    cargado = cargarXML.obtenerGrafo(idTarea)
  File "/home/viki/pgrado/learning_by_imitation/scripts/cargarXML.py", line 43, in obtenerGrafo
    for s in r.sensor:
  File "lxml.objectify.pyx", line 218, in lxml.objectify.ObjectifiedElement.**getattr** (src/lxml/lxml.objectify.c:3563)
  File "lxml.objectify.pyx", line 437, in lxml.objectify._lookupChildOrRaise (src/lxml/lxml.objectify.c:5873)
AttributeError: no such child: sensor

**Comment by gevovlockas** [comment]
---

**Comment by juanps90** [comment]
Qué tarea estabas intentando hacer?

Cargando la que viene por defecto está tirando esto:

```
if self.hasColor(self.dataSensor[Const.SENSOR_VISION_HEAD_ID], color):
TypeError: hasColor() takes exactly 2 arguments (3 given)
```

**Comment by juanps90** [comment]
Logré replicar el mismo error que se reporta, pero ahora no más.

**Comment by juanps90** [comment]
OK, ahora lo logro replicar. Subo el XML que genera, que por cierto se guarda en pgrado, no en la carpeta de scripts como creí.
[TareaTest_0_0.xml.zip](https://github.com/juanps90/pgrado/files/188922/TareaTest_0_0.xml.zip)

**Comment by juanps90** [comment]
Confirmo que teniendo el nombre en "TareaTest_0" y dando en "ejecutar" con un nodo de maestro recien lanzado y tira ese error.

El archivo XML se generó a partir de demostraciones.

**Comment by gandres2003** [comment]
Corregido el error. 
Se estaba dando porque existe una sección de parámetros (asociados a los nodos) y la misma esperaba parámetros (lecutras de los sensores) para todos los nodos de la topología. El problema es que el último nodo de toda demostración, el INIT, no tiene parámetros y ahí fallaba.

Para prevenir futuros comportamientos que puedan no tener asociados lecturas de sensores (¿? no imagino ninguno pero...) en esa sección se hace un chequeo de control apra evitar que falle.

PD: Gracias por el XML de prueba.

**Comment by juanps90** [comment]
Confirmo el fix. Saludos.
