### ISSUE TITLE
No está detectando la línea en el aprendizaje

### ISSUE THREAD

**Issue by juanps90** [juanps90/pgrado#24]
En el modo de demostración no está detectando nunca la línea. Se observa cómo detecta los objetos pero no la línea.

[no_anda_ir_linea.ogv.zip](https://github.com/juanps90/pgrado/files/188910/no_anda_ir_linea.ogv.zip)

**Comment by juanps90** [comment]
Realmente no lo logro hacer andar... Si alguien se anima a ver si también le pasa estaría bueno.

**Comment by juaneliel** [comment]
ahi me fijo

**Comment by juaneliel** [comment]
El problema es con los sensores de vrep que no estan andando bien si imprimis los sensores en ningun momento manda el valor de negro...igualmente como avanzar y localizar usan los mismos sensores los colores estan harcodeados y no se aprende colores se sigue siempre la linea negra

**Comment by gevovlockas** [comment]
Solucionado. Ahora detecta varios colores.
