### ISSUE TITLE
Meter GO sin HERE detiene la ejecución

### ISSUE THREAD

**Issue by juanps90** [juanps90/pgrado#28]
Si se apreta go después del come, el robot abandona la ejecución de la tarea.

```
comando  go
antes de go
entro en go
ATENCION no hay nada nuevo aprendido
None
recibo comando 13 1
comando  come
ATENCION solo se puede hacer come cuando se este ejecutando
None
```

**Comment by juaneliel** [comment]
el codigo queda asi:

if fase=="come":
    print "ATENCION no hay nada nuevo aprendido"
    msg.data = [2,2] 
    estado.publish(msg)  
    fase="ejecutar"
    return
