### ISSUE TITLE
Array de sensores

### ISSUE THREAD

**Issue by gevovlockas** [juanps90/pgrado#9]
Hacer un array con datos de sensores para mandaro todos los datos de una.

**Comment by juaneliel** [comment]
Como hago para tomar este?

**Comment by juaneliel** [comment]
Como tomo el issue en  github?

El 26/2/16, gevovlockas <notifications@github.com> escribió:
> Hacer un array con datos de sensores para mandaro todos los datos de una.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/juanps90/pgrado/issues/9


-- 
saludos

**Comment by juaneliel** [comment]
ya lo halle :D
